### ISSUE TITLE
More work to port to multiPane

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguide-microprofile-config#183]
See PR#185 for the initial port.

Other work to be done:

- [ ] placement of the content in the pod for "ConfigureViaInject" step - it shifts at the end.
- [ ] playground step - need instruction and point to mark it complete; remove browser since not used.
- [ ] put focus to a widget during transition of instruction
- [ ] with the initial port, "ConfigureViaInject" is the only step with the pod other than the playground. I did not include the pod to the other config steps. It may be something good to discuss with the team thru internal playground or even with Jay/Megan thru the upcoming external playground.
- [ ] Convert all messages to use the message files.
- [ ] Review the .json file to edit out phrases such as '..in the following browser'.
- [ ] Add server.xml to all the editors after enabling the feature as a read-only file.

- [ ] We also need to discuss the welcome.html file.  I think it should have a different URL, like 'https://mycarvendor.openliberty.io/car-inventory' since it does not display any car types.  Then, on the 'Providing optional default values' step, we should change the instruction back to changing the URL to 'https://mycarvendor.openliberty.io/car-types' and hitting enter.
